run("Duplicate...", " ");
run("8-bit");
run("Gaussian Blur...", "sigma=3");
setAutoThreshold("Default dark");
//run("Threshold...");
setAutoThreshold("Default dark");
//setThreshold(37, 255);
setOption("BlackBackground", false);
run("Convert to Mask");
run("Analyze Particles...", "exclude add");
